---
DNS1:
  100.64.33.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: 100.64.33.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 100.64.33.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
